service: kmu-sdms-api
frameworkVersion: "4"

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - "src/**"
    - "!serverless.yml"
    - "!node_modules/**"
    - "!package*.json"
    - "!README.md"
    - "!legacy_web_scraper/**"
    - "!layer/**"
    - "!envs/**"
    - "!.git/**"
    - "!.gitignore"
    - "!requirements.txt"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!**/__pycache__/**"

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-2
  timeout: 25
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true
  environment:
    STAGE: ${self:provider.stage}
    SUPABASE_URL: ${file(envs/config.${self:provider.stage}.json):SUPABASE_URL}
    SUPABASE_API_KEY: ${file(envs/config.${self:provider.stage}.json):SUPABASE_API_KEY}

layers:
  AppDependencies:
    path: layer
    name: ${self:provider.stage}-app-dependencies
    description: "스마트 기숙사 관리 시스템 Python 의존성"
    compatibleRuntimes:
      - python3.11

functions:
  getRooms:
    name: ${self:provider.stage}-api-getRooms
    handler: src.handlers.rooms_handler.get_all
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: get
          path: /rooms

  getNotices:
    name: ${self:provider.stage}-api-getNotices
    handler: src.handlers.notices_handler.get_paginated
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: get
          path: /notices

  getNoticeById:
    name: ${self:provider.stage}-api-getNoticeByID
    handler: src.handlers.notices_handler.get_one
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: get
          path: /notice

  getStudents:
    name: ${self:provider.stage}-api-getStudents
    handler: src.handlers.students_handler.get_all
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: get
          path: /students

  getStudentsByRoom:
    name: ${self:provider.stage}-api-getStudentsByRoom
    handler: src.handlers.students_handler.get_by_room
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: get
          path: /students/{roomId}

  createNotice:
    name: ${self:provider.stage}-api-createNotice
    handler: src.handlers.notices_handler.create
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: post
          path: /notice

  deleteNotice:
    name: ${self:provider.stage}-api-deleteNotice
    handler: src.handlers.notices_handler.delete
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: delete
          path: /notice

  updateNotice:
    name: ${self:provider.stage}-api-updateNotice
    handler: src.handlers.notices_handler.update
    layers:
      - { Ref: AppDependenciesLambdaLayer }
    events:
      - httpApi:
          method: put
          path: /notice
